# Generated by Django 5.2 on 2025-05-06 20:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Cierre')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Efectivo Esperado (Sistema)')),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Ventas Tarjeta')),
                ('total_transfer_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Ventas Transferencia')),
                ('grand_total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total General de Ventas (Calculado)')),
                ('total_sales_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad Total de Ventas')),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Efectivo Contado en Caja')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Diferencia de Efectivo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas / Observaciones')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Cierra')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-closing_time'],
            },
        ),
    ]
