# Generated by Django 5.2 on 2025-05-06 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashclosure',
            name='opening_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Apertura del Período'),
            preserve_default=False,
        ),
    ]
