# Generated by Django 5.2 on 2025-05-17 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Proveedor')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Marca/Fabricante'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.brand', verbose_name='Marca/Fabricante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Artículo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remito_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Remito Prov.')),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del Ingreso')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Ingreso de Stock (Remito)',
                'verbose_name_plural': 'Ingresos de Stock (Remitos)',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='StockEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad Ingresada')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Compra Unit.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product', verbose_name='Producto Ingresado')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.stockentry', verbose_name='Ingreso de Stock')),
            ],
            options={
                'verbose_name': 'Detalle de Ingreso de Stock',
                'verbose_name_plural': 'Detalles de Ingresos de Stock',
                'unique_together': {('stock_entry', 'product')},
            },
        ),
    ]
