# Generated by Django 5.2 on 2025-05-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
    ]
