# Generated by Django 5.2 on 2025-05-03 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_amount_received_sale_change_given_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['client_name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='client',
            name='tax_condition',
            field=models.CharField(choices=[('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('MO', 'Monotributista'), ('EX', 'Exento')], default='CF', max_length=2, verbose_name='Condición IVA'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El formato debe ser XX-XXXXXXXX-X.', regex='^\\d{2}-\\d{8}-\\d{1}$')], verbose_name='CUIT/CUIL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=150, verbose_name='Nombre o Razón Social'),
        ),
    ]
