# Generated by Django 5.2 on 2025-05-04 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_client_options_client_tax_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Descuento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Descuento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Total (Final)'),
        ),
    ]
